### ISSUE TITLE
🚀 : Profile Pictures Optimizations For Homepage 

### ISSUE THREAD

**Issue by xuelink** [langxapp/langx#633]
**Is your feature request related to a problem? Please describe.**
Profile pictures on the homepage lack optimization, resulting in potential slowdowns in loading times and inefficient use of bandwidth.

**Describe the solution you'd like**
Implementing a URL-based solution to allow dynamic resizing and quality adjustment of profile pictures on the homepage:
```url
https://db.langx.io/v1/storage/buckets/[bucketId]/files/[fileId]/preview?width=30&height=30&quality=45&project=[ProjectID]
```
This solution allows for specifying width, height, and quality parameters, ensuring optimized image sizes for faster loading times without sacrificing visual quality.

**Describe alternatives you've considered**
Consider server-side image resizing and optimization solutions, but these may require more development resources and maintenance.

**Additional context**
Implementing this feature will enhance the user experience by optimizing profile picture loading times on the homepage. 

_Contributor: @DH-555_

_If you want speed up process of this issue, please send 🚀 as a reaction._

**Comment by DH-555** [comment]
Potential parameters that best fit for the main page previews:

Height and width: 190
Quality: 45

**Comment by xuelink** [comment]
https://appwrite.io/docs/references/cloud/client-web/storage#getFilePreview

**Comment by xuelink** [comment]
> Potential parameters that best fit for the main page previews:
> 
> Height and width: 190 Quality: 45

gonna do this suggestion
