### ISSUE TITLE
Flag for languages to learn / practice

### ISSUE THREAD

**Issue by pastanton** [langxapp/langx#645]
Problem:
Currently, users can only post a single native language and then add additional languages and include one of three fluency level. This does not allow users to include all the languages they know or are familiar with or if they do, it does not allow them to flag which languages they are interested in knowing. 

As a user, I would like to be able to include all the languages I know, include my fluency level, and flag whether or not I am interested in better learning a language (for beginner to fluent), or interested in helping others learn that language (for fluent or native). I would also like the option to not flag the language as either option. I would like this ternary option so that other users can see my preferences for conversion. And if my preferences are stored and indexed, they may be used for better language partner recommendations within the app. This can help with user engagement and minimize disinterested conversation partners.

**Comment by pastanton** [comment]
I should elaborate that right now there's only an option for languages you want to learn and your mother tongue.

Ideally, I would hope to be able to include additional languages as well.

**Comment by xuelink** [comment]
You are right and its also requested and upvoted feature here https://github.com/langxapp/langx/issues/438 

That's why im closing this issue, is it okey for you ? @pastanton

**Comment by pastanton** [comment]
I wasn't sure if this was included, but sounds good to close.

**Comment by xuelink** [comment]
I also pinged you within the other issue ! :)
